name: Playwright Tests in Docker

on:
  push:
    branches: [main, master, les30-tests-github-actions]
  pull_request:
    branches: [main, master, les30-tests-github-actions]
  workflow_dispatch:

jobs:
  playwright-tests:
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/playwright:v1.39.0-jammy
      options: --init --ipc=host

    env:
      BASE_URL: https://guest:welcome2qauto@qauto.forstudy.space/
      HTTP_USERNAME: guest
      HTTP_PASSWORD: welcome2qauto
      USER_EMAIL: kureninovavika2@gmail.com
      USER_PASSWORD: Test1234A

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install project dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - name: Show files after tests
        if: always()
        run: |
          pwd
          ls -la